### ISSUE TITLE
containerd hash might be wrong

### ISSUE THREAD

**Issue by jamesoncollins** [paralin/buildroot#16]
https://github.com/skiffos/buildroot/blob/c16417c668b8543a69459e3145eba238d6780d07/package/containerd/containerd.hash#L2

I've tried on a couple machines, and I get a hash match error on this.

```
ERROR: containerd-1.5.7.tar.gz has wrong sha256 hash:
ERROR: expected: 7d8f7014a74b063da9cdf7fe8673db8dc338747efdbb9b6a6a919d5137b1987e
ERROR: got     : 09be0cedea77568029aa0c7be9a323b89fa6886b402b5d223780a05b8c7cd45a

```

**Comment by paralin** [comment]
Submitted a few days ago to the mailing list:

 - https://lists.buildroot.org/pipermail/buildroot/2021-November/627161.html
 - https://lists.buildroot.org/pipermail/buildroot/2021-November/627162.html

Already fixed / added the new hash: https://github.com/skiffos/buildroot/commit/3606b9b7fe94b749c7337fae6cccfd3d67f508f4
